"""Add OTP columns to users

Revision ID: 04633d0967d8
Revises: 38bbcffef685
Create Date: 2026-01-08 00:39:42.876596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04633d0967d8'
down_revision: Union[str, Sequence[str], None] = '38bbcffef685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
