"""Updated tables and fields

Revision ID: 08973ba6996a
Revises: d7e8f9a0b1c2
Create Date: 2026-02-24 00:38:31.708760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08973ba6996a'
down_revision: Union[str, Sequence[str], None] = 'd7e8f9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', 'REMOTE', name='employmenttype'), nullable=False))
    op.add_column('jobs', sa.Column('experience_required', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='jobstatus'),
               existing_nullable=False)
    op.drop_column('jobs', 'processing_error')
    op.drop_column('jobs', 'jd_file_url')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('jobs', 'processing_status')
    op.drop_column('jobs', 'education')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('processing_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('jd_file_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='jobstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'application_deadline')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'experience_required')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
