"""Removed unwanted models

Revision ID: a82288bbb529
Revises: e98aa7228052
Create Date: 2026-02-22 02:00:26.245202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a82288bbb529'
down_revision: Union[str, Sequence[str], None] = 'e98aa7228052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables before parent tables (FK order)
    op.drop_table('skill_synonyms')
    op.drop_table('skill_subtopics')
    op.drop_table('skill_dependencies')
    op.drop_table('skill_ontology')
    op.drop_table('learning_roadmaps')
    op.drop_table('resume_job_analysis')
    op.drop_table('shortlists')
    op.drop_index(op.f('idx_sga_candidate'), table_name='skill_gap_analyses')
    op.drop_index(op.f('idx_sga_resume_jd_hash'), table_name='skill_gap_analyses')
    op.drop_table('skill_gap_analyses')
    op.add_column('candidate_profiles', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('candidate_profiles', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidate_profiles', sa.Column('is_profile_complete', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('candidate_profiles', sa.Column('profile_score', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.execute("UPDATE users SET role = 'JOB_SEEKER' WHERE role IS NULL")
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('JOB_SEEKER', 'RECRUITER', name='user_role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('JOB_SEEKER', 'RECRUITER', name='user_role'),
               nullable=True)
    op.drop_column('candidate_profiles', 'is_public')
    op.drop_column('candidate_profiles', 'profile_score')
    op.drop_column('candidate_profiles', 'is_profile_complete')
    op.drop_column('candidate_profiles', 'skills')
    op.drop_column('candidate_profiles', 'location')
    op.drop_column('candidate_profiles', 'bio')
    op.create_table('skill_dependencies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['skill_ontology.id'], name=op.f('skill_dependencies_prerequisite_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_ontology.id'], name=op.f('skill_dependencies_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_dependencies_pkey')),
    sa.UniqueConstraint('skill_id', 'prerequisite_id', name=op.f('skill_dependencies_skill_id_prerequisite_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('skill_gap_analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('jd_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jd_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('match_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_jd_skills', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hard_skill_match', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('soft_skill_match', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extra_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('gap_report', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ontology_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('skill_gap_analyses_candidate_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('skill_gap_analyses_resume_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_gap_analyses_pkey'))
    )
    op.create_index(op.f('idx_sga_resume_jd_hash'), 'skill_gap_analyses', ['resume_id', 'jd_hash'], unique=False)
    op.create_index(op.f('idx_sga_candidate'), 'skill_gap_analyses', ['candidate_id'], unique=False)
    op.create_table('skill_subtopics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subtopic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_ontology.id'], name=op.f('skill_subtopics_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_subtopics_pkey'))
    )
    op.create_table('shortlists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SHORTLISTED', 'REJECTED', name='resume_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('shortlists_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('shortlists_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shortlists_pkey'))
    )
    op.create_table('resume_job_analysis',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('resume_job_analysis_job_id_fkey')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('resume_job_analysis_resume_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_job_analysis_pkey'))
    )
    op.create_table('learning_roadmaps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recommended_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('learning_roadmaps_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('learning_roadmaps_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_roadmaps_pkey'))
    )
    op.create_table('skill_synonyms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('synonym', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_ontology.id'], name=op.f('skill_synonyms_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_synonyms_pkey')),
    sa.UniqueConstraint('synonym', name=op.f('skill_synonyms_synonym_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('skill_ontology',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canonical_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('base_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ontology_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_ontology_pkey')),
    sa.UniqueConstraint('canonical_name', name=op.f('skill_ontology_canonical_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
