"""updated fields in resume model

Revision ID: bf2b25736d2d
Revises: b5b8db157b1d
Create Date: 2026-02-08 23:12:09.686100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf2b25736d2d'
down_revision: Union[str, Sequence[str], None] = 'b5b8db157b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('jobs', sa.Column('processing_status', sa.String(length=20), nullable=False))
    op.add_column('jobs', sa.Column('experience_level', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('resume_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('resumes', 'parsed_text')
    op.drop_column('resumes', 'parsed_skills')
    op.drop_column('resumes', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('parsed_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('parsed_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'resume_data')
    op.drop_column('resumes', 'title')
    op.drop_column('jobs', 'processing_error')
    op.drop_column('jobs', 'education')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'processing_status')
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
