"""remove field like location, required_skills, exprienced_required from job model

Revision ID: e1c3a8691ccf
Revises: 4777fbc27d79
Create Date: 2026-01-08 07:56:44.879107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c3a8691ccf'
down_revision: Union[str, Sequence[str], None] = '4777fbc27d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'experience_required')
    op.drop_column('jobs', 'required_skills')
    op.add_column('recruiters', sa.Column('job_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiters', 'job_description')
    op.add_column('jobs', sa.Column('required_skills', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('experience_required', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
